In [ ]:
import folium
import geopy
from geopy.geocoders import Nominatim
from folium.plugins import HeatMap
import certifi
import ssl
import pandas as pd
import re

from plotly.subplots import make_subplots
from plotly import subplots
import plotly.graph_objs as go
from plotly.offline import plot
import plotly.offline as pyo

import warnings

warnings.simplefilter('ignore')

In [ ]:
ctx = ssl.create_default_context(cafile=certifi.where())
geopy.geocoders.options.default_ssl_context = ctx

In [ ]:
df = pd.read_excel("leads_export.xlsx")

In [ ]:
day_count = day_count.reset_index()
day_count.sort_index(inplace=True)

In [ ]:
day_count.sort_values('Created_at', inplace=True)

In [ ]:
pcv = df['Fully rented'].value_counts()

In [ ]:
pcv_2 = df['Object type'].value_counts().reset_index()

In [ ]:
# Create a subplot
fig = make_subplots(rows=1, cols=1)

# Create a trace for the trend line
trace = go.Scatter(
    x=day_count['Created_at'],
    y=day_count['count'],
    mode='lines+markers',
    name='Count Over Time',
    line=dict(color='lightcoral')
)


# Add trace to the subplot
fig.add_trace(trace, row=1, col=1)


# Customize layout
fig.update_layout(
    title='Leads Timeline',
    xaxis_title='Date',
    yaxis_title='Count',
    template='plotly_dark',
    plot_bgcolor='#333333', #'rgba(79, 83, 88, 0)',
    paper_bgcolor='#333333', #'rgba(79, 83, 88, 0.4)',
    font_color='rgba(255, 255, 255, 1)',
    font_size=15,
    autosize=True,
    xaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)',  # White gridlines for the x-axis
    ),
    yaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)'   # White gridlines for the y-axis
    )
)

In [ ]:
pyo.plot(fig, filename='trend_line_plot.html', auto_open=False)

'trend_line_plot.html'

In [ ]:
# Create a subplot
fig = make_subplots(rows=1, cols=1, specs=[[{"type": "pie"}]])

# Create a trace for the pie plot

trace = go.Pie(
    labels=pcv.index,
    values=pcv.values,
    textinfo='label+percent',
    insidetextorientation='radial',
    hole=.4
)

# Add trace to the subplot
fig.add_trace(trace, row=1, col=1)


# Customize layout
fig.update_layout(
    title='Fully rented',
    template='plotly_dark',
    plot_bgcolor='#333333', #'rgba(79, 83, 88, 0)',
    paper_bgcolor='#333333', #'rgba(79, 83, 88, 0.4)',
    font_color='rgba(255, 255, 255, 1)',
    font_size=15,
    autosize=True,
    xaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)',  # White gridlines for the x-axis
    ),
    yaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)'   # White gridlines for the y-axis
    )
)

fig.update_traces(marker=dict(colors=['lightcoral', 'cornflowerblue']))

In [ ]:
pyo.plot(fig, filename='pie_plot.html', auto_open=False)

'pie_plot.html'

In [ ]:
# Create a subplot
fig = make_subplots(rows=1, cols=1)

# Create a trace for the pie plot

trace = go.Bar(
    x=pcv_2['Object type'],
    y=pcv_2['count'],
    # text=pcv_2.values,
    # textposition='auto',
    marker_color=['lightcoral', 'lightpink', 'lavender', 'cadetblue', 'cornflowerblue', 'midnightblue']
)

# Add trace to the subplot
fig.add_trace(trace, row=1, col=1)


# Customize layout
fig.update_layout(
    title='Object type',
    xaxis_title='Type',
    yaxis_title='Count',
    template='plotly_dark',
    plot_bgcolor='#333333', #'rgba(79, 83, 88, 0)',
    paper_bgcolor='#333333', #'rgba(79, 83, 88, 0.4)',
    font_color='rgba(255, 255, 255, 1)',
    font_size=15,
    autosize=True,
    xaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)',  # White gridlines for the x-axis
    ),
    yaxis=dict(
        gridcolor='rgba(255, 255, 255, 1)'   # White gridlines for the y-axis
    )
)

# fig.update_traces(marker=dict(colors=['lightcoral', 'cornflowerblue']))

In [ ]:
pyo.plot(fig, filename='bar_plot.html', auto_open=False)

'bar_plot.html'

In [ ]:
df.columns.tolist()

['ID',
 'E-mail',
 'First name',
 'Last name',
 'phone',
 'News',
 '100-day sales guarantee',
 'Selling price',
 'Value analysis',
 'Retirement',
 'Created_at',
 'source',
 'Attachments/Files',
 'Property and location',
 'Object type',
 'Street',
 'Postal code',
 'Location',
 'House number',
 'Federal State',
 'Property information',
 'House type',
 'Year of construction',
 'Living area',
 'Residential units',
 'Commercial space',
 'Commercial units',
 'Plot area',
 'Built',
 'Secluded location',
 'Developed',
 'Number of rooms',
 'Number of floors',
 'Object condition',
 'equipment',
 'Guest toilet',
 'Fully rented',
 'balcony',
 'Elevator',
 'Attic',
 'cellar',
 'parking',
 'Column1',
 'Modernizations',
 'Roof',
 'Window',
 'Lines',
 'Heating',
 'facade',
 'bathroom',
 'Interior fittings',
 'Floor plan design',
 'Current usage',
 'Damage/defects',
 'rental income (cold rent)',
 'Information on special rights']

In [ ]:
sc = pd.DataFrame(df['Federal State'].value_counts()).reset_index()

In [ ]:
l_counts = pd.DataFrame(df['Location'].value_counts()).reset_index()

In [ ]:
l_counts

                  Location  count
0            Aschaffenburg    101
1            Test location     94
2             Grossostheim     15
3                    wdawd     11
4                  Norheim     11
..                     ...    ...
197  Neuburg an der Kammel      1
198               Eisenach      1
199               Mühlheim      1
200               Krombach      1
201               Marklohe      1

[202 rows x 2 columns]

In [ ]:
int("".join(re.findall('[0-9]+', str("013212 123"))))

13212123

In [ ]:
geolocator = Nominatim(user_agent="shahzaib881")

def get_lat_lon(city):
    try:
        location = geolocator.geocode(city)
        if location:
            try:
                lat = location.latitude
            except:
                lat = None
            try:
                lon = location.longitude
            except:
                lon = None
            try:
                ad_len = len(location.address.split(", "))
            except:
                ad_len = 0
            try:
                cn = location.address.split(", ")[0]
            except:
                cn = None
            try:
                if ad_len > 5:
                    ct = location.address.split(", ")[-4]
                else:
                    ct = location.address.split(", ")[1]
            except:
                ct = None
            try:
                if ad_len > 5:
                    st = location.address.split(", ")[-3]
                elif ad_len < 5:
                    st = None
                else:
                    st = location.address.split(", ")[2]
            except:
                st = None
            try:
                if ad_len > 5:
                    zp = location.address.split(", ")[-2]
                elif ad_len < 5:
                    zp = None
                else:
                    zp = location.address.split(", ")[3]
                try:
                    zp = int("".join(re.findall('[0-9]+', str(zp))))
                except:
                    ct = st
                    st = zp
                    zp = None
            except:
                zp = None
            return ([lat, lon], cn, ct, st, zp)
    except Exception as e:
        print(f"Error getting coordinates for {city}: {e}")
    return None

In [ ]:
locss = l_counts['Location'].apply(get_lat_lon)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Tiefenbach&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=a&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=a&format=json&limit=1

Error getting coordinates for a: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=a&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=3&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=DILLINGEN&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Hoechstadt&format=json&limit=1

In [ ]:
l_counts['coordinates'] = locss.apply(lambda x: x[0] if x != None else None)
l_counts['correct_name'] = locss.apply(lambda x: x[1] if x != None else None)
l_counts['city_name'] = locss.apply(lambda x: x[2] if x != None else None)
l_counts['state_name'] = locss.apply(lambda x: x[3] if x != None else None)
l_counts['zip_code'] = locss.apply(lambda x: x[4] if x != None else None)

In [ ]:
l_counts

,Location,count,coordinates,correct_name,city_name,state_name,zip_code
0,Aschaffenburg,101,"[49.9740542, 9.1493636]",Aschaffenburg,None,None,NaN
1,Test location,94,"[50.908659650000004, 6.22375492939141]",Film + Test Location,Kreis Düren,Nordrhein-Westfalen,52457.0
2,Grossostheim,15,"[49.9207462, 9.0755904]",Großostheim,Landkreis Aschaffenburg,Bayern,63762.0
3,wdawd,11,None,None,None,None,NaN
4,Norheim,11,"[49.810658, 7.8143823]",Norheim,Landkreis Bad Kreuznach,Rheinland-Pfalz,NaN
...,...,...,...,...,...,...,...
197,Neuburg an der Kammel,1,"[48.3035791, 10.3618238]",Neuburg an der Kammel,Landkreis Günzburg,Bayern,86476.0
198,Eisenach,1,"[50.9747134, 10.3193565]",Eisenach,Wartburgkreis,Thüringen,99817.0
199,Mühlheim,1,"[48.3801078, 8.6985101]",Mühlheim,Landkreis Rottweil,Baden-Württemberg,72172.0
200,Krombach,1,"[50.828899, 14.7011224]",Krompach,Liberecký kraj,Severovýchod,47157.0
201,Marklohe,1,"[52.6690306, 9.1568113]",Marklohe,Landkreis Nienburg/Weser,Niedersachsen,31608.0

In [ ]:
df['coordinates'] = pd.merge(left=df[['Location']], right=l_counts[['Location', 'coordinates']], how='left', on='Location')['coordinates']
df['correct_name'] = pd.merge(left=df[['Location']], right=l_counts[['Location', 'correct_name']], how='left', on='Location')['correct_name']
df['city_name'] = pd.merge(left=df[['Location']], right=l_counts[['Location', 'city_name']], how='left', on='Location')['city_name']
df['state_name'] = pd.merge(left=df[['Location']], right=l_counts[['Location', 'state_name']], how='left', on='Location')['state_name']
df['zip_code'] = pd.merge(left=df[['Location']], right=l_counts[['Location', 'zip_code']], how='left', on='Location')['zip_code']

In [ ]:
df['city_name']

0            سرگودھا ڈویژن
1              Kreis Düren
2                     None
3                     None
4                     None
              ...
496                   None
497    Landkreis Offenbach
498                   None
499          Wetteraukreis
500          Wetteraukreis
Name: city_name, Length: 501, dtype: object

In [ ]:
nlcount = l_counts[l_counts['coordinates'].notna()]

In [ ]:
world_map = folium.Map(location=[51.1657, 10.4515], zoom_start=6)
heat_data = [[coords[0], coords[1], count] for coords, count in zip(nlcount['coordinates'], nlcount['count'])]
HeatMap(heat_data).add_to(world_map)

# Add city markers with count as popups or tooltips
for i, row in nlcount.iterrows():
    lat, lon = row['coordinates']
    count = row['count']
    city = row['Location']
    folium.CircleMarker(
        location=[lat, lon],
        radius=3,  # Adjust marker size (in pixels)
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.6,
        popup=f"{city}: {count}",  # Shows when clicked
        tooltip=f"{city}: {count}"  # Shows when hovered
    ).add_to(world_map)

world_map.save("city_heatmap.html")

________________________________

In [ ]:
import geopandas as gdp

In [ ]:
cnt = gdp.read_file("geoBoundaries-DEU-ADM3-all.zip")

In [ ]:
cnt.rename(columns={'shapeName': 'city_name'}, inplace=True)

In [ ]:
city_counts = pd.DataFrame(df['city_name'].value_counts()).reset_index()

In [ ]:
cnt['city_name'] = cnt['city_name'].str.split(",").apply(lambda x: x[0])

city_counts['city_name'] = city_counts['city_name'].str.replace("Landkreis ", "")
city_counts['city_name'] = city_counts['city_name'].str.replace(" Landkreis", "")

city_counts['city_name'] = city_counts['city_name'].str.replace("Stadt ", "")
city_counts['city_name'] = city_counts['city_name'].str.replace(" Stadt", "")

cnt['city_name'] = cnt['city_name'].str.replace("Landkreis ", "")
cnt['city_name'] = cnt['city_name'].str.replace(" Landkreis", "")

cnt['city_name'] = cnt['city_name'].str.replace("Stadt ", "")
cnt['city_name'] = cnt['city_name'].str.replace(" Stadt", "")

cnt['city_name'] = cnt['city_name'].str.replace(",", "")

In [ ]:
cnt2 = gdp.read_file("geoBoundaries-DEU-ADM2-all.zip")
cnt2.rename(columns={'shapeName': 'city_name'}, inplace=True)

In [ ]:
for i in cnt['city_name'].tolist():
  if 'Kreis' in i:
    print(i)

Rems-Murr-Kreis
Main-Tauber-Kreis
Neckar-Odenwald-Kreis
Rhein-Neckar-Kreis
Schwarzwald-Baar-Kreis
Alb-Donau-Kreis
Main-Kinzig-Kreis
Main-Taunus-Kreis
Rheingau-Taunus-Kreis
Lahn-Dill-Kreis
Schwalm-Eder-Kreis
Werra-MeiÃner-Kreis
Rhein-Kreis Neuss
Rhein-Erft-Kreis
Oberbergischer Kreis
Rheinisch-Bergischer Kreis
Rhein-Sieg-Kreis
Ennepe-Ruhr-Kreis
MÃ¤rkischer Kreis
Rhein-Lahn-Kreis
Rhein-HunsrÃ¼ck-Kreis
Rhein-Pfalz-Kreis
Saarpfalz-Kreis
Unstrut-Hainich-Kreis
Ilm-Kreis
Saale-Holzland-Kreis
Saale-Orla-Kreis

In [ ]:
check = pd.merge(left=city_counts, right=cnt, on='city_name', how='left')

In [ ]:
check_notna = gdp.GeoDataFrame(check[check['shapeID'].notna()])

In [ ]:
import branca.colormap as cm

In [ ]:
# Create a base folium map (centered on Germany, adjust location and zoom if needed)
m = folium.Map(location=[51.1657, 10.4515], zoom_start=6)

# Create a color map based on the 'count' column
min_count = check_notna['count'].min()
max_count = check_notna['count'].max()
colormap = cm.LinearColormap(colors=['blue', 'green', 'yellow', 'red'], vmin=min_count, vmax=max_count)

# Add the city boundaries to the map using GeoJson and dynamically color them based on 'count'
folium.GeoJson(
    check_notna,
    style_function=lambda feature: {
        'fillColor': colormap(feature['properties']['count']),  # Dynamic color based on count
        'color': 'black',  # Boundary color
        'weight': 2,       # Boundary thickness
        'fillOpacity': 0.6,  # Opacity of the fill
    },
    tooltip=folium.GeoJsonTooltip(fields=['city_name', 'count'])  # Tooltip showing city name and count
).add_to(m)

# Add the color map legend
colormap.caption = 'City Count'
colormap.add_to(m)

# Save the map to an HTML file
m.save("city_boundaries_colored.html")